/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PriceCache {
    timestamp: bigint;
    price: number;
}
export interface Coin {
    id: string;
    currentPrice: number;
    marketCap?: number;
    name: string;
    priceChange24h?: number;
    symbol: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PriceRange {
    low: number;
    high: number;
}
export interface TimeframeParams {
    timeframe: string;
    intervalNanos: bigint;
    priceData: Array<PriceCache>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PortfolioSummary {
    coins: number;
    profitLossDollar: number;
    avgCost: number;
    currentValue: number;
    profitLossPercent: number;
}
export interface PortfolioGoal {
    isCompleted: boolean;
    name: string;
    target: number;
}
export interface UserProfile {
    name: string;
}
export interface http_header {
    value: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTopCryptosToCache(newTopCryptos: Array<Coin>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPriceAlert(price: number): Promise<void>;
    deletePriceAlert(price: number): Promise<void>;
    getAlerts(): Promise<Array<[number, boolean]>>;
    getAllCryptosLiveData(): Promise<string>;
    getCachedPriceHistory(): Promise<Array<PriceCache>>;
    getCachedTopCryptos(): Promise<Array<Coin>>;
    getCachedUNIPriceHistory(): Promise<Array<PriceCache>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyHighLowFromCache(): Promise<PriceRange>;
    getHistoricalDataRange(): Promise<{
        end: bigint;
        start: bigint;
    }>;
    getHistoricalPriceHistory(params: TimeframeParams): Promise<Array<PriceCache>>;
    getICPLivePrice(): Promise<string>;
    getPortfolioGoals(): Promise<Array<PortfolioGoal>>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getResampledPriceHistory(intervalNanos: bigint): Promise<Array<PriceCache>>;
    getUNILivePrice(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordNewICPPrice(price: number): Promise<void>;
    recordNewUNIPrice(price: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePortfolioGoals(goals: Array<PortfolioGoal>): Promise<void>;
    toggleAlertStatus(price: number): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Coin as _Coin, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTopCryptosToCache(arg0: Array<Coin>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTopCryptosToCache(to_candid_vec_n1(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTopCryptosToCache(to_candid_vec_n1(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createPriceAlert(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPriceAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPriceAlert(arg0);
            return result;
        }
    }
    async deletePriceAlert(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePriceAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePriceAlert(arg0);
            return result;
        }
    }
    async getAlerts(): Promise<Array<[number, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return result;
        }
    }
    async getAllCryptosLiveData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCryptosLiveData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCryptosLiveData();
            return result;
        }
    }
    async getCachedPriceHistory(): Promise<Array<PriceCache>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedPriceHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedPriceHistory();
            return result;
        }
    }
    async getCachedTopCryptos(): Promise<Array<Coin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedTopCryptos();
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedTopCryptos();
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCachedUNIPriceHistory(): Promise<Array<PriceCache>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedUNIPriceHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedUNIPriceHistory();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDailyHighLowFromCache(): Promise<PriceRange> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyHighLowFromCache();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyHighLowFromCache();
            return result;
        }
    }
    async getHistoricalDataRange(): Promise<{
        end: bigint;
        start: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalDataRange();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalDataRange();
            return result;
        }
    }
    async getHistoricalPriceHistory(arg0: TimeframeParams): Promise<Array<PriceCache>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalPriceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalPriceHistory(arg0);
            return result;
        }
    }
    async getICPLivePrice(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPLivePrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPLivePrice();
            return result;
        }
    }
    async getPortfolioGoals(): Promise<Array<PortfolioGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioGoals();
            return result;
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return result;
        }
    }
    async getResampledPriceHistory(arg0: bigint): Promise<Array<PriceCache>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResampledPriceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResampledPriceHistory(arg0);
            return result;
        }
    }
    async getUNILivePrice(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUNILivePrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUNILivePrice();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordNewICPPrice(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordNewICPPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordNewICPPrice(arg0);
            return result;
        }
    }
    async recordNewUNIPrice(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordNewUNIPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordNewUNIPrice(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePortfolioGoals(arg0: Array<PortfolioGoal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePortfolioGoals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePortfolioGoals(arg0);
            return result;
        }
    }
    async toggleAlertStatus(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAlertStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAlertStatus(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Coin_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coin): Coin {
    return from_candid_record_n8(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    currentPrice: number;
    marketCap: [] | [number];
    name: string;
    priceChange24h: [] | [number];
    symbol: string;
}): {
    id: string;
    currentPrice: number;
    marketCap?: number;
    name: string;
    priceChange24h?: number;
    symbol: string;
} {
    return {
        id: value.id,
        currentPrice: value.currentPrice,
        marketCap: record_opt_to_undefined(from_candid_opt_n9(uploadFile, downloadFile, value.marketCap)),
        name: value.name,
        priceChange24h: record_opt_to_undefined(from_candid_opt_n9(uploadFile, downloadFile, value.priceChange24h)),
        symbol: value.symbol
    };
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coin>): Array<Coin> {
    return value.map((x)=>from_candid_Coin_n7(uploadFile, downloadFile, x));
}
function to_candid_Coin_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Coin): _Coin {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(uploadFile, downloadFile, value);
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    currentPrice: number;
    marketCap?: number;
    name: string;
    priceChange24h?: number;
    symbol: string;
}): {
    id: string;
    currentPrice: number;
    marketCap: [] | [number];
    name: string;
    priceChange24h: [] | [number];
    symbol: string;
} {
    return {
        id: value.id,
        currentPrice: value.currentPrice,
        marketCap: value.marketCap ? candid_some(value.marketCap) : candid_none(),
        name: value.name,
        priceChange24h: value.priceChange24h ? candid_some(value.priceChange24h) : candid_none(),
        symbol: value.symbol
    };
}
function to_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Coin>): Array<_Coin> {
    return value.map((x)=>to_candid_Coin_n2(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
