/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceAlertStatus = IDL.Record({
  'isTriggered' : IDL.Bool,
  'price' : IDL.Float64,
});
export const PriceCache = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const TimeframeParams = IDL.Record({
  'timeframe' : IDL.Text,
  'intervalNanos' : IDL.Int,
  'priceData' : IDL.Vec(PriceCache),
});
export const PortfolioSummary = IDL.Record({
  'coins' : IDL.Float64,
  'profitLossDollar' : IDL.Float64,
  'avgCost' : IDL.Float64,
  'currentValue' : IDL.Float64,
  'profitLossPercent' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getAlerts' : IDL.Func([], [IDL.Vec(PriceAlertStatus)], ['query']),
  'getCachedPriceHistory' : IDL.Func([], [IDL.Vec(PriceCache)], ['query']),
  'getHistoricalDataRange' : IDL.Func(
      [],
      [IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int })],
      [],
    ),
  'getHistoricalPriceHistory' : IDL.Func(
      [TimeframeParams],
      [IDL.Vec(PriceCache)],
      [],
    ),
  'getICPLivePrice' : IDL.Func([], [IDL.Text], []),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getResampledPriceHistory' : IDL.Func([IDL.Nat], [IDL.Vec(PriceCache)], []),
  'getTopCryptos' : IDL.Func([], [IDL.Text], []),
  'recordNewICPPrice' : IDL.Func([IDL.Float64], [], []),
  'toggleAlertStatus' : IDL.Func([IDL.Float64], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceAlertStatus = IDL.Record({
    'isTriggered' : IDL.Bool,
    'price' : IDL.Float64,
  });
  const PriceCache = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const TimeframeParams = IDL.Record({
    'timeframe' : IDL.Text,
    'intervalNanos' : IDL.Int,
    'priceData' : IDL.Vec(PriceCache),
  });
  const PortfolioSummary = IDL.Record({
    'coins' : IDL.Float64,
    'profitLossDollar' : IDL.Float64,
    'avgCost' : IDL.Float64,
    'currentValue' : IDL.Float64,
    'profitLossPercent' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getAlerts' : IDL.Func([], [IDL.Vec(PriceAlertStatus)], ['query']),
    'getCachedPriceHistory' : IDL.Func([], [IDL.Vec(PriceCache)], ['query']),
    'getHistoricalDataRange' : IDL.Func(
        [],
        [IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int })],
        [],
      ),
    'getHistoricalPriceHistory' : IDL.Func(
        [TimeframeParams],
        [IDL.Vec(PriceCache)],
        [],
      ),
    'getICPLivePrice' : IDL.Func([], [IDL.Text], []),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getResampledPriceHistory' : IDL.Func([IDL.Nat], [IDL.Vec(PriceCache)], []),
    'getTopCryptos' : IDL.Func([], [IDL.Text], []),
    'recordNewICPPrice' : IDL.Func([IDL.Float64], [], []),
    'toggleAlertStatus' : IDL.Func([IDL.Float64], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };