/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coin = IDL.Record({
  'id' : IDL.Text,
  'currentPrice' : IDL.Float64,
  'marketCap' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'priceChange24h' : IDL.Opt(IDL.Float64),
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceCache = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PriceRange = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
});
export const TimeframeParams = IDL.Record({
  'timeframe' : IDL.Text,
  'intervalNanos' : IDL.Int,
  'priceData' : IDL.Vec(PriceCache),
});
export const PortfolioGoal = IDL.Record({
  'isCompleted' : IDL.Bool,
  'name' : IDL.Text,
  'target' : IDL.Float64,
});
export const PortfolioSummary = IDL.Record({
  'coins' : IDL.Float64,
  'profitLossDollar' : IDL.Float64,
  'avgCost' : IDL.Float64,
  'currentValue' : IDL.Float64,
  'profitLossPercent' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTopCryptosToCache' : IDL.Func([IDL.Vec(Coin)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPriceAlert' : IDL.Func([IDL.Float64], [], []),
  'deletePriceAlert' : IDL.Func([IDL.Float64], [], []),
  'getAlerts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Bool))],
      ['query'],
    ),
  'getCachedPriceHistory' : IDL.Func([], [IDL.Vec(PriceCache)], ['query']),
  'getCachedTopCryptos' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyHighLowFromCache' : IDL.Func([], [PriceRange], ['query']),
  'getHistoricalDataRange' : IDL.Func(
      [],
      [IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int })],
      [],
    ),
  'getHistoricalPriceHistory' : IDL.Func(
      [TimeframeParams],
      [IDL.Vec(PriceCache)],
      [],
    ),
  'getICPLivePrice' : IDL.Func([], [IDL.Text], []),
  'getPortfolioGoals' : IDL.Func([], [IDL.Vec(PortfolioGoal)], ['query']),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getResampledPriceHistory' : IDL.Func([IDL.Nat], [IDL.Vec(PriceCache)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordNewICPPrice' : IDL.Func([IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePortfolioGoals' : IDL.Func([IDL.Vec(PortfolioGoal)], [], []),
  'toggleAlertStatus' : IDL.Func([IDL.Float64], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coin = IDL.Record({
    'id' : IDL.Text,
    'currentPrice' : IDL.Float64,
    'marketCap' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'priceChange24h' : IDL.Opt(IDL.Float64),
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceCache = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PriceRange = IDL.Record({ 'low' : IDL.Float64, 'high' : IDL.Float64 });
  const TimeframeParams = IDL.Record({
    'timeframe' : IDL.Text,
    'intervalNanos' : IDL.Int,
    'priceData' : IDL.Vec(PriceCache),
  });
  const PortfolioGoal = IDL.Record({
    'isCompleted' : IDL.Bool,
    'name' : IDL.Text,
    'target' : IDL.Float64,
  });
  const PortfolioSummary = IDL.Record({
    'coins' : IDL.Float64,
    'profitLossDollar' : IDL.Float64,
    'avgCost' : IDL.Float64,
    'currentValue' : IDL.Float64,
    'profitLossPercent' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTopCryptosToCache' : IDL.Func([IDL.Vec(Coin)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPriceAlert' : IDL.Func([IDL.Float64], [], []),
    'deletePriceAlert' : IDL.Func([IDL.Float64], [], []),
    'getAlerts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Bool))],
        ['query'],
      ),
    'getCachedPriceHistory' : IDL.Func([], [IDL.Vec(PriceCache)], ['query']),
    'getCachedTopCryptos' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyHighLowFromCache' : IDL.Func([], [PriceRange], ['query']),
    'getHistoricalDataRange' : IDL.Func(
        [],
        [IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int })],
        [],
      ),
    'getHistoricalPriceHistory' : IDL.Func(
        [TimeframeParams],
        [IDL.Vec(PriceCache)],
        [],
      ),
    'getICPLivePrice' : IDL.Func([], [IDL.Text], []),
    'getPortfolioGoals' : IDL.Func([], [IDL.Vec(PortfolioGoal)], ['query']),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getResampledPriceHistory' : IDL.Func([IDL.Nat], [IDL.Vec(PriceCache)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordNewICPPrice' : IDL.Func([IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePortfolioGoals' : IDL.Func([IDL.Vec(PortfolioGoal)], [], []),
    'toggleAlertStatus' : IDL.Func([IDL.Float64], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };