/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PortfolioSummary {
  'coins' : number,
  'profitLossDollar' : number,
  'avgCost' : number,
  'currentValue' : number,
  'profitLossPercent' : number,
}
export interface PriceAlertStatus { 'isTriggered' : boolean, 'price' : number }
export interface PriceCache { 'timestamp' : bigint, 'price' : number }
export interface TimeframeParams {
  'timeframe' : string,
  'intervalNanos' : bigint,
  'priceData' : Array<PriceCache>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getAlerts' : ActorMethod<[], Array<PriceAlertStatus>>,
  'getCachedPriceHistory' : ActorMethod<[], Array<PriceCache>>,
  'getHistoricalDataRange' : ActorMethod<
    [],
    { 'end' : bigint, 'start' : bigint }
  >,
  'getHistoricalPriceHistory' : ActorMethod<
    [TimeframeParams],
    Array<PriceCache>
  >,
  'getICPLivePrice' : ActorMethod<[], string>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getResampledPriceHistory' : ActorMethod<[bigint], Array<PriceCache>>,
  'getTopCryptos' : ActorMethod<[], string>,
  'recordNewICPPrice' : ActorMethod<[number], undefined>,
  'toggleAlertStatus' : ActorMethod<[number], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];