/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coin {
  'id' : string,
  'currentPrice' : number,
  'marketCap' : [] | [number],
  'name' : string,
  'priceChange24h' : [] | [number],
  'symbol' : string,
}
export interface PortfolioGoal {
  'isCompleted' : boolean,
  'name' : string,
  'target' : number,
}
export interface PortfolioSummary {
  'coins' : number,
  'profitLossDollar' : number,
  'avgCost' : number,
  'currentValue' : number,
  'profitLossPercent' : number,
}
export interface PriceCache { 'timestamp' : bigint, 'price' : number }
export interface PriceRange { 'low' : number, 'high' : number }
export interface TimeframeParams {
  'timeframe' : string,
  'intervalNanos' : bigint,
  'priceData' : Array<PriceCache>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTopCryptosToCache' : ActorMethod<[Array<Coin>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPriceAlert' : ActorMethod<[number], undefined>,
  'deletePriceAlert' : ActorMethod<[number], undefined>,
  'getAlerts' : ActorMethod<[], Array<[number, boolean]>>,
  'getCachedPriceHistory' : ActorMethod<[], Array<PriceCache>>,
  'getCachedTopCryptos' : ActorMethod<[], Array<Coin>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyHighLowFromCache' : ActorMethod<[], PriceRange>,
  'getHistoricalDataRange' : ActorMethod<
    [],
    { 'end' : bigint, 'start' : bigint }
  >,
  'getHistoricalPriceHistory' : ActorMethod<
    [TimeframeParams],
    Array<PriceCache>
  >,
  'getICPLivePrice' : ActorMethod<[], string>,
  'getPortfolioGoals' : ActorMethod<[], Array<PortfolioGoal>>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getResampledPriceHistory' : ActorMethod<[bigint], Array<PriceCache>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordNewICPPrice' : ActorMethod<[number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePortfolioGoals' : ActorMethod<[Array<PortfolioGoal>], undefined>,
  'toggleAlertStatus' : ActorMethod<[number], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];